import { jsPDF } from 'jspdf';

const BRAND_ORANGE = [234, 88, 12];
const DARK = [30, 20, 10];
const MUTED = [120, 100, 80];
const LIGHT_BG = [253, 249, 244];
const WHITE = [255, 255, 255];

function addPageHeader(doc, pageNum) {
  // Top bar
  doc.setFillColor(...BRAND_ORANGE);
  doc.rect(0, 0, 210, 10, 'F');

  // Brand name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...WHITE);
  doc.text('LAUNCHORA', 14, 6.5);
  doc.text(`Page ${pageNum}`, 196, 6.5, { align: 'right' });
}

function addSection(doc, title, content, y, pageNum) {
  const margin = 14;
  const maxWidth = 182;

  // Check if we need a new page
  if (y > 260) {
    doc.addPage();
    pageNum++;
    addPageHeader(doc, pageNum);
    y = 22;
  }

  // Section label pill
  doc.setFillColor(253, 237, 220);
  doc.roundedRect(margin, y, maxWidth, 7, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(...BRAND_ORANGE);
  doc.text(title.toUpperCase(), margin + 4, y + 4.8);
  y += 10;

  // Content
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(...DARK);

  if (Array.isArray(content)) {
    content.forEach((item, i) => {
      const lines = doc.splitTextToSize(`• ${item}`, maxWidth - 4);
      lines.forEach(line => {
        if (y > 270) { doc.addPage(); pageNum++; addPageHeader(doc, pageNum); y = 22; }
        doc.text(line, margin + 4, y);
        y += 5.5;
      });
      y += 1;
    });
  } else if (content) {
    const lines = doc.splitTextToSize(String(content), maxWidth - 4);
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); pageNum++; addPageHeader(doc, pageNum); y = 22; }
      doc.text(line, margin + 4, y);
      y += 5.5;
    });
  }

  y += 6;
  return { y, pageNum };
}

export function exportProductPDF(product) {
  const d = product.generated_data || {};
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let pageNum = 1;

  // ── COVER PAGE ──────────────────────────────────────────────
  // Full background
  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 0, 210, 297, 'F');

  // Top accent bar
  doc.setFillColor(...BRAND_ORANGE);
  doc.rect(0, 0, 210, 56, 'F');

  // Brand
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...WHITE);
  doc.text('LAUNCHORA', 14, 20);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(255, 200, 150);
  doc.text('DONKOV VENTURES', 14, 26);

  // Product type badge
  doc.setFillColor(255, 255, 255, 0.25);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...WHITE);
  doc.text(`${product.product_type}  ·  ${product.platform}`, 14, 40);

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...WHITE);
  const titleLines = doc.splitTextToSize(d.title || product.title || 'Product Report', 180);
  doc.text(titleLines, 14, 50);

  // Subtitle card
  const subtitleY = 66 + (titleLines.length - 1) * 10;
  doc.setFillColor(...WHITE);
  doc.roundedRect(14, subtitleY, 182, 22, 3, 3, 'F');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  const subtitleLines = doc.splitTextToSize(d.subtitle || '', 170);
  doc.text(subtitleLines, 23, subtitleY + 9);

  // Promise section
  const promiseY = subtitleY + 32;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND_ORANGE);
  doc.text('THE PROMISE', 14, promiseY);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  const promiseLines = doc.splitTextToSize(d.promise || '', 182);
  doc.text(promiseLines, 14, promiseY + 6);

  // Price box
  doc.setFillColor(...BRAND_ORANGE);
  doc.roundedRect(14, 240, 80, 28, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...WHITE);
  doc.text('SUGGESTED PRICE', 22, 250);
  doc.setFontSize(22);
  doc.text(`$${d.price_min}–$${d.price_max}`, 22, 262);

  // CTA box
  doc.setFillColor(253, 237, 220);
  doc.roundedRect(104, 240, 92, 28, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...BRAND_ORANGE);
  doc.text('CALL TO ACTION', 112, 250);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...DARK);
  const ctaLines = doc.splitTextToSize(d.cta || '', 78);
  doc.text(ctaLines, 112, 258);

  // Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by Launchora · ${new Date().toLocaleDateString()}`, 14, 290);

  // ── PAGE 2: PRODUCT DETAILS ───────────────────────────────
  doc.addPage();
  pageNum = 2;
  addPageHeader(doc, pageNum);

  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 10, 210, 287, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text('Product Details', 14, 22);
  let y = 30;

  let state = { y, pageNum };
  state = addSection(doc, 'Target Audience', d.audience, state.y, state.pageNum);
  state = addSection(doc, 'Format', d.format, state.y, state.pageNum);
  state = addSection(doc, 'Selling Angle', d.selling_angle, state.y, state.pageNum);
  state = addSection(doc, 'Buyer Profile', d.buyer_profile, state.y, state.pageNum);
  state = addSection(doc, 'Benefits', d.benefits, state.y, state.pageNum);

  // ── PAGE 3: PRODUCT STRUCTURE ─────────────────────────────
  doc.addPage();
  pageNum = state.pageNum + 1;
  addPageHeader(doc, pageNum);

  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 10, 210, 287, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text('Product Structure', 14, 22);
  state = { y: 30, pageNum };

  state = addSection(doc, 'Structure', d.structure, state.y, state.pageNum);
  state = addSection(doc, 'Content Draft', d.content_draft, state.y, state.pageNum);

  // ── PAGE 4: LISTING & MARKETING ──────────────────────────
  doc.addPage();
  pageNum = state.pageNum + 1;
  addPageHeader(doc, pageNum);

  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 10, 210, 287, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text('Listing & Marketing', 14, 22);
  state = { y: 30, pageNum };

  state = addSection(doc, 'Listing Title', d.listing_title, state.y, state.pageNum);
  state = addSection(doc, 'Listing Description', d.listing_description, state.y, state.pageNum);
  state = addSection(doc, 'Keywords', d.keywords, state.y, state.pageNum);
  state = addSection(doc, 'Visual Direction', d.visual_direction, state.y, state.pageNum);
  state = addSection(doc, 'Cover Concept', d.cover_concept, state.y, state.pageNum);

  // ── PAGE 5: PLATFORM GUIDANCE ────────────────────────────
  const pg = d.platform_guidance || {};
  doc.addPage();
  pageNum = state.pageNum + 1;
  addPageHeader(doc, pageNum);

  doc.setFillColor(...LIGHT_BG);
  doc.rect(0, 10, 210, 287, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...DARK);
  doc.text(`Platform Guide: ${product.platform}`, 14, 22);
  state = { y: 30, pageNum };

  state = addSection(doc, 'Why This Platform', pg.why_this_platform, state.y, state.pageNum);
  state = addSection(doc, 'Pricing Strategy', pg.pricing_strategy, state.y, state.pageNum);
  state = addSection(doc, 'Publishing Steps', pg.publishing_steps, state.y, state.pageNum);
  state = addSection(doc, 'Pro Tips', pg.pro_tips, state.y, state.pageNum);
  state = addSection(doc, 'Mistakes to Avoid', pg.mistakes_to_avoid, state.y, state.pageNum);

  // Save
  const filename = `${(d.title || 'product').replace(/[^a-z0-9]/gi, '-').toLowerCase()}-launchora.pdf`;
  doc.save(filename);
}