import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// ── TEXT FILE GENERATORS ───────────────────────────────────────────────────

function generateProductTXT(d, product) {
  const safe = (v) => (v && String(v).trim()) ? String(v).trim() : '(not generated)';
  const lines = [
    '============================================================',
    'LAUNCHORA — PRODUCT OVERVIEW',
    '============================================================',
    '',
    `Title:    ${safe(d.title || product.title)}`,
    `Subtitle: ${safe(d.subtitle)}`,
    `Type:     ${safe(product.product_type)}`,
    `Niche:    ${safe(product.niche)}`,
    `Tone:     ${safe(product.tone)}`,
    `Platform: ${safe(product.platform)}`,
    '',
    '── PROMISE ──────────────────────────────────────────────────',
    safe(d.promise),
    '',
    '── TARGET AUDIENCE ──────────────────────────────────────────',
    safe(d.audience),
    '',
    '── BUYER PROFILE ────────────────────────────────────────────',
    safe(d.buyer_profile),
    '',
    '── SELLING ANGLE ────────────────────────────────────────────',
    safe(d.selling_angle),
    '',
    '── KEY BENEFITS ─────────────────────────────────────────────',
    Array.isArray(d.benefits) && d.benefits.length
      ? d.benefits.map((b, i) => `  ${i + 1}. ${b}`).join('\n')
      : '(not generated)',
    '',
    '── PRODUCT STRUCTURE ────────────────────────────────────────',
    Array.isArray(d.structure) && d.structure.length
      ? d.structure.map((s, i) => `  ${i + 1}. ${s}`).join('\n')
      : '(not generated)',
    '',
    '── PRICING ──────────────────────────────────────────────────',
    `Recommended: $${d.price_min || 17}–$${d.price_max || 37}`,
    safe(d.price_rationale),
    '',
    '── VISUAL DIRECTION ─────────────────────────────────────────',
    safe(d.visual_direction),
    '',
    '── COVER CONCEPT ────────────────────────────────────────────',
    safe(d.cover_concept),
    '',
    '── FORMAT ───────────────────────────────────────────────────',
    safe(d.format),
    '',
    '============================================================',
    'Generated by Launchora',
    '============================================================',
  ];
  return lines.join('\n');
}

function generateListingTXT(d, product) {
  const safe = (v) => (v && String(v).trim()) ? String(v).trim() : '(not generated)';
  return [
    '============================================================',
    'LAUNCHORA — PLATFORM LISTING COPY',
    '============================================================',
    `Product: ${safe(d.title || product.title)}`,
    `Platform: ${safe(product.platform)}`,
    '',
    '── LISTING TITLE ────────────────────────────────────────────',
    safe(d.listing_title),
    '',
    '── LISTING DESCRIPTION ──────────────────────────────────────',
    safe(d.listing_description),
    '',
    '── SEO KEYWORDS ─────────────────────────────────────────────',
    Array.isArray(d.keywords) && d.keywords.length
      ? d.keywords.join(', ')
      : '(not generated)',
    '',
    '── SEO META DESCRIPTION ─────────────────────────────────────',
    safe(d.seo_meta_description),
    '',
    '── PLATFORM CTA ─────────────────────────────────────────────',
    safe(d.platform_cta || d.cta),
    '',
    '── PRICE RANGE ──────────────────────────────────────────────',
    `$${d.price_min || 17}–$${d.price_max || 37}`,
    '',
    '============================================================',
    'Generated by Launchora',
    '============================================================',
  ].join('\n');
}

function generatePlatformGuideTXT(d, product) {
  const pg = d.platform_guidance || {};
  const safe = (v) => (v && String(v).trim()) ? String(v).trim() : '(not generated)';
  return [
    '============================================================',
    'LAUNCHORA — PLATFORM LAUNCH GUIDE',
    '============================================================',
    `Product: ${safe(d.title || product.title)}`,
    `Platform: ${safe(product.platform)}`,
    '',
    '── WHY THIS PLATFORM ────────────────────────────────────────',
    safe(pg.why_this_platform),
    '',
    '── PLATFORM AUDIENCE ────────────────────────────────────────',
    safe(pg.platform_audience),
    '',
    '── PRICING STRATEGY ─────────────────────────────────────────',
    safe(pg.pricing_strategy),
    '',
    '── THUMBNAIL GUIDANCE ───────────────────────────────────────',
    safe(pg.thumbnail_guidance),
    '',
    '── LAUNCH PLAN ──────────────────────────────────────────────',
    safe(pg.launch_plan),
    '',
    '── PRO TIPS ─────────────────────────────────────────────────',
    Array.isArray(pg.pro_tips) && pg.pro_tips.length
      ? pg.pro_tips.map((t, i) => `  ${i + 1}. ${t}`).join('\n')
      : '(not generated)',
    '',
    '── MISTAKES TO AVOID ────────────────────────────────────────',
    Array.isArray(pg.mistakes_to_avoid) && pg.mistakes_to_avoid.length
      ? pg.mistakes_to_avoid.map((m, i) => `  ${i + 1}. ${m}`).join('\n')
      : '(not generated)',
    '',
    '============================================================',
    'Generated by Launchora',
    '============================================================',
  ].join('\n');
}

function generateContentTXT(d, product) {
  const title = d.title || product.title || 'Product';
  const lines = [
    '============================================================',
    title,
    '============================================================',
    '',
  ];
  if (d.promise) lines.push(`PROMISE: ${d.promise}`, '');
  if (d.audience) lines.push(`FOR: ${d.audience}`, '');
  lines.push('── FULL CONTENT ─────────────────────────────────────────────', '');
  lines.push(d.content_draft || '(Content not yet generated)');
  return lines.join('\n');
}

// ── ZIP BUILDER (no dependencies) ─────────────────────────────────────────

function buildZip(files) {
  const enc = new TextEncoder();
  const toBytes = (d) => typeof d === 'string' ? enc.encode(d) : new Uint8Array(d);

  const crcTable = (() => {
    const t = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      t[i] = c;
    }
    return t;
  })();

  const crc32 = (data) => {
    let crc = 0xFFFFFFFF;
    for (let i = 0; i < data.length; i++) crc = crcTable[(crc ^ data[i]) & 0xFF] ^ (crc >>> 8);
    return (crc ^ 0xFFFFFFFF) >>> 0;
  };

  const u16 = (n) => { const b = new Uint8Array(2); new DataView(b.buffer).setUint16(0, n, true); return b; };
  const u32 = (n) => { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, n, true); return b; };
  const concat = (...arrays) => {
    const total = arrays.reduce((s, a) => s + a.length, 0);
    const out = new Uint8Array(total);
    let off = 0;
    for (const a of arrays) { out.set(a, off); off += a.length; }
    return out;
  };

  const entries = [];
  let offset = 0;
  const now = new Date();
  const dosDate = ((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate();
  const dosTime = (now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1);

  for (const { name, data } of files) {
    const nameBytes = enc.encode(name);
    const fileData = toBytes(data);
    const crc = crc32(fileData);
    const localHeader = concat(
      new Uint8Array([0x50, 0x4B, 0x03, 0x04]),
      u16(20), u16(0), u16(0),
      u16(dosTime), u16(dosDate),
      u32(crc), u32(fileData.length), u32(fileData.length),
      u16(nameBytes.length), u16(0), nameBytes,
    );
    entries.push({ name, nameBytes, crc, size: fileData.length, offset, dosTime, dosDate, localHeader, fileData });
    offset += localHeader.length + fileData.length;
  }

  const cdParts = entries.map(e => concat(
    new Uint8Array([0x50, 0x4B, 0x01, 0x02]),
    u16(20), u16(20), u16(0), u16(0),
    u16(e.dosTime), u16(e.dosDate),
    u32(e.crc), u32(e.size), u32(e.size),
    u16(e.nameBytes.length), u16(0), u16(0), u16(0), u16(0),
    u32(0), u32(e.offset), e.nameBytes,
  ));

  const centralDir = concat(...cdParts);
  const eocd = concat(
    new Uint8Array([0x50, 0x4B, 0x05, 0x06]),
    u16(0), u16(0),
    u16(entries.length), u16(entries.length),
    u32(centralDir.length), u32(offset), u16(0),
  );

  return concat(...entries.flatMap(e => [e.localHeader, e.fileData]), centralDir, eocd);
}

function uint8ToBase64(bytes) {
  let binary = '';
  const chunk = 8192;
  for (let i = 0; i < bytes.length; i += chunk) {
    binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
  }
  return btoa(binary);
}

// ── HANDLER ────────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);

  try {
    // Auth
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ success: false, error: 'Unauthorized', details: 'No authenticated user' }, { status: 401 });
    }

    // Parse body
    let body;
    try {
      body = await req.json();
    } catch (e) {
      return Response.json({ success: false, error: 'Invalid request body', details: e.message }, { status: 400 });
    }

    const { productId } = body;
    console.log(`[generateZip] productId: ${productId}`);

    if (!productId) {
      return Response.json({ success: false, error: 'productId is required', details: 'Pass productId in the request body' }, { status: 400 });
    }

    // Fetch product by ID
    let product;
    try {
      product = await base44.entities.Product.get(productId);
    } catch (e) {
      console.error(`[generateZip] Failed to fetch product: ${e.message}`);
      return Response.json({ success: false, error: 'Product not found', details: e.message }, { status: 404 });
    }

    if (!product) {
      return Response.json({ success: false, error: 'Product not found', details: `No product with id ${productId}` }, { status: 404 });
    }

    const d = product.generated_data || {};
    console.log(`[generateZip] Product found: "${d.title || product.title}" | status: ${product.status}`);
    console.log(`[generateZip] has content_draft: ${!!d.content_draft} | has listing_title: ${!!d.listing_title} | blocks: ${(d.product_blocks || []).length}`);

    // Generate text files
    const safeName = (d.title || product.title || 'product')
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .replace(/\s+/g, '_')
      .substring(0, 40) || 'product';

    const readmeTxt = [
      'LAUNCHORA — PRODUCT PACKAGE',
      '============================',
      '',
      `Product: ${d.title || product.title}`,
      `Type: ${product.product_type} | Platform: ${product.platform}`,
      `Generated: ${new Date().toISOString()}`,
      '',
      'INCLUDED FILES:',
      `  Product.txt          → Product overview, benefits, structure, pricing`,
      `  Listing.txt          → Platform listing title, description, keywords`,
      `  Content.txt          → Full product content draft`,
      `  PlatformGuide.txt    → Platform-specific launch strategy`,
      '',
      'HOW TO USE:',
      '  1. Copy Listing.txt into your platform listing (Etsy / Gumroad / etc.)',
      '  2. Use PlatformGuide.txt as your step-by-step launch plan',
      '  3. Reference Content.txt to edit or repurpose the raw content',
      '',
      'Generated by Launchora',
    ].join('\n');

    const files = [
      { name: 'README.txt', data: readmeTxt },
      { name: 'Product.txt', data: generateProductTXT(d, product) },
      { name: 'Listing.txt', data: generateListingTXT(d, product) },
      { name: 'Content.txt', data: generateContentTXT(d, product) },
      { name: 'PlatformGuide.txt', data: generatePlatformGuideTXT(d, product) },
    ];

    console.log(`[generateZip] Building ZIP with ${files.length} files...`);
    const zipBytes = buildZip(files);
    console.log(`[generateZip] ZIP built — size: ${zipBytes.length} bytes`);

    // Upload to Base44 storage
    const zipBlob = new Blob([zipBytes], { type: 'application/zip' });
    const zipFile = new File([zipBlob], `${safeName}_launchora.zip`, { type: 'application/zip' });

    console.log(`[generateZip] Uploading ZIP to storage...`);
    const uploadResult = await base44.integrations.Core.UploadFile({ file: zipFile });
    console.log(`[generateZip] Upload result:`, JSON.stringify(uploadResult));

    if (!uploadResult?.file_url) {
      return Response.json({
        success: false,
        error: 'Upload succeeded but no file URL was returned',
        details: JSON.stringify(uploadResult),
      }, { status: 500 });
    }

    const fileName = `${safeName}_launchora.zip`;
    console.log(`[generateZip] Done! fileUrl: ${uploadResult.file_url}`);

    return Response.json({
      success: true,
      fileUrl: uploadResult.file_url,
      fileName,
      fileSize: zipBytes.length,
      generatedAt: new Date().toISOString(),
    });

  } catch (error) {
    console.error('[generateZip] Unhandled error:', error.message, error.stack);
    return Response.json({
      success: false,
      error: error.message || 'Unknown error',
      details: error.stack || '',
    }, { status: 500 });
  }
});